name: Snyk Code Security Scan

on: 
  workflow_dispatch:
  push:
    branches: [ "development" ]

permissions:
  id-token: write
  contents: read

jobs:
  # Build and Package HealthPoint application
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Mono
      run: |
        sudo apt update
        sudo apt install -y mono-complete
    
    - name: Restore Nuget Packages
      run: mono nuget.exe restore snyk_scan_test.sln

    - name: Build
      run: msbuild snyk_scan_test.sln /p:Configuration=Release
