name: Snyk Code Security Scan

on: 
  workflow_dispatch:
  push:
    branches: [ "development" ]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Mono
      run: |
        sudo apt update
        sudo apt install -y mono-complete
    - name: Install .NET Framework Developer Pack
      run: |
        sudo apt install -y referenceassemblies-pcl
        
    - name: Download NuGet CLI
      run: |
        sudo apt install -y wget
        wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -O nuget.exe
    
    - name: Restore Nuget Packages
      run: mono nuget.exe restore snyk_scan_test.sln
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/dotnet@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
